- FrontEnd/StyleSheets/Chatbook.nb
- PacletInfo.wl
- README.md
- Source/Chatbook.wl
- Source/Debug.wl
- Source/ErrorUtils.wl
- Source/Errors.wl
- Source/Serialization.wl
- Source/Streaming.wl
- Source/UI.wl
- Source/Utils.wl
- SourceSSE/ServerSentEventUtils.wl
- Tests/SSETests.wlt
- Tests/Streaming.wlt
@theodoregray @chriswolfram @rhennigan @batracos FYI: This PR changed the publisher ID and root context from ConnorGray to Wolfram. You should rebase any branches you may be working on.
> chore: Move from the ConnorGray publisher ID to the Wolfram publisher ID

- Source/APIFunctions/APIFunctions.wl
- Source/APIFunctions/APIs/Common.wl
- Source/APIFunctions/APIs/OpenAI.wl
- Source/APIFunctions/Chat.wl
- Source/APIFunctions/ImageSynthesize.wl
- Source/APIFunctions/TextSynthesize.wl
More authentication options for the API functions.
> Add SystemCredential and Environment

- Documentation/English/ReferencePages/ChatEvaluate.nb
- Documentation/English/ReferencePages/ChatObject.nb
- Documentation/English/ReferencePages/CreateChat.nb
- Documentation/English/ReferencePages/TextSynthesize.nb
Added documentation page for function exported in the `` Wolfram`APIFunctions` ``
- ChatObject
- CreateChat
- ChatEvaluate
- ImageSynthesize
- TextSynthesize
> Documentation for API functions

- docs/Development.md
> docs: Document instructions for updating the Chatbook.nb stylesheet

- Source/Chatbook/Actions.wl
This hooks up the "Stop" button in active chat output cells:
> Added `StopChat` action

- Source/Chatbook/Actions.wl
> Workaround for system credentials in cloud

- PacletInfo.wl
- Source/Chatbook/Actions.wl
- Source/Chatbook/CreateChatNotebook.wl
This is actually quite usable in cloud now:
> Better cloud support

- PacletInfo.wl
- Source/Chatbook/Formatting.wl
> Set `Method -> "Active"` for inline tool responses

- PacletInfo.wl
- Source/Chatbook/Actions.wl
- Source/Chatbook/Common.wl
- Source/Chatbook/Formatting.wl
- Source/Chatbook/Prompting.wl
- Source/Chatbook/Serialization.wl
- Source/Chatbook/Tools.wl
Sample notebook: https://www.wolframcloud.com/obj/rhennigan/Published/WolframAlphaToolExamples.nb
> Wolfram Alpha Tool

- Source/Chatbook/Formatting.wl
This fixes a few issues with nested formatting directives in chat output markdown formatting. To test specific markdown, you can paste it over an existing chat output and use toggle formatting from the menu:
> Misc markdown improvements

- PacletInfo.wl
- Source/Chatbook/Actions.wl
- Source/Chatbook/Formatting.wl
- Source/Chatbook/Prompting.wl
- Source/Chatbook/Tools.wl
https://www.wolframcloud.com/obj/rhennigan/Published/ToolUseBenchmark_2023-06-16.nb
> Tool improvements

- Assets/SandboxMessages.wl
- LLMConfiguration/Personas/CodeAssistant/LLMConfiguration.wl
- LLMConfiguration/Personas/CodeWriter/LLMConfiguration.wl
- LLMConfiguration/Personas/PlainChat/LLMConfiguration.wl
- PacletInfo.wl
- Source/Chatbook/Actions.wl
- Source/Chatbook/CreateChatNotebook.wl
- Source/Chatbook/Explode.wl
- Source/Chatbook/Formatting.wl
- Source/Chatbook/Main.wl
- Source/Chatbook/Sandbox.wl
- Source/Chatbook/Tools.wl
Sample notebook using default tools: https://www.wolframcloud.com/obj/rhennigan/Published/BirdnardoTools.nb
For testing custom tools (gpt-4 is recommended):
```
CreateNotebook[
"ChatEnabled",
"ToolsEnabled" -> True,
"Tools" -> {
LLMTool[
"cityPopulationFinder",
"city" -> "City",
#city[ "Population" ] &
],
LLMTool[
{
"imageSynthesizer",
"Use generative AI to create an image from a prompt. Use the resulting markdown link in your response."
},
"prompt" -> "String",
ImageSynthesize[ #prompt ] &
]
}
]
```
> More tool improvements

- Source/Chatbook/Actions.wl
The links in all cases point to https://platform.openai.com/docs/models/overview
> Override some OpenAI error messages to provide more helpful information

- Developer/Resources/Styles.wl
- FrontEnd/StyleSheets/Chatbook.nb
> Add chat block styles to format menu

- Source/Chatbook/FrontEnd.wl
> Fix an `$IterationLimit` error in cloud when clicking Evaluate/Insert buttons

- Source/Chatbook/Actions.wl
- Source/Chatbook/Formatting.wl
Code used to create notebook:
```
CreateNotebook[
"ChatEnabled",
"LLMEvaluator" -> "PlainChat",
"Model" -> "gpt-4",
"Tools" -> {
LLMTool[
"FlipCoins",
{ "count" -> "Integer" },
Function[
If[ ChoiceDialog[ "Flip a coin?" ],
StringRiffle @ RandomChoice[ { "heads", "tails" }, #count ],
"Sorry, I'm all out of coins"
]
]
]
}
]
```
> Allow dialogs during tool evaluations

- Source/Chatbook/Common.wl
- Source/Chatbook/PersonaInstaller.wl
> Add a dialog suggesting install from URL if the channel framework isn't working

- Source/Chatbook/PersonaInstaller.wl
- Source/Chatbook/UI.wl
> Resize persona icons in preferences to consistent sizes

- Assets/AIAssistant/Prompts/Default.md
- Developer/Resources/Styles.wl
- FrontEnd/StyleSheets/Chatbook.nb
- Source/Chatbook/Actions.wl
- Source/Chatbook/ChatGroups.wl
- Source/Chatbook/CreateChatNotebook.wl
- Source/Chatbook/FrontEnd.wl
- Source/Chatbook/Main.wl
Here's a demo notebook: https://www.wolframcloud.com/obj/rhennigan/Published/ChatGroupPromptExamples.nb
> Define prompting at the Section/Subsection levels that's additively inherited within the cell group

- Source/Chatbook/FrontEnd.wl
- Source/Chatbook/Main.wl
> Added `CurrentChatSettings`

- Source/Chatbook/Sandbox.wl
> Fix for Graph expressions created by sandbox kernels not formatting correctly

- Source/Chatbook/ChatMessages.wl
> prevent recursion failures during tool prompting when an LLMTool contains Template content

- Source/Chatbook/Serialization.wl
> Bugfix: Avoid exceeding token limits for cells that contain inline images

- Source/Chatbook/Formatting.wl
- Source/Chatbook/Serialization.wl
> Support for markdown tables in input and output

- Source/Chatbook/SendChat.wl
- Source/Chatbook/Settings.wl
- Source/Chatbook/Tools.wl
- Source/Chatbook/UI.wl
Example notebook: https://www.wolframcloud.com/obj/rhennigan/Published/ToolCallingFrequency.nb
> Customizable tool call frequency

- Source/Chatbook/Menus.wl
- Source/Chatbook/UI.wl
> Bugfix: Add scrollbars to submenus when large to avoid content clipping

- Source/Chatbook/UI.wl
> Show checkmark next to "User" role as default

- Source/Chatbook/SendChat.wl
> Bugfix: Do not include generated cells that appear after the chat input in the chat context

- Source/Chatbook/Formatting.wl
> Preserve order of cells when inserting via code block button tray

- FrontEnd/StyleSheets/Chatbook.nb
- Source/Chatbook/ChatHistory.wl
- Source/Chatbook/CloudToolbar.wl
- Source/Chatbook/PreferencesContent.wl
- Source/Chatbook/SendChat.wl
- Source/Chatbook/Settings.wl
> Initial version of a chat preferences dialog

- Source/Chatbook/PreferencesContent.wl
- Source/Chatbook/Settings.wl
- Source/Chatbook/ToolManager.wl
> Add "Tools" tab to cloud preferences

- Source/Chatbook/CloudToolbar.wl
> Add an "Insert Chat Cell" menu to the cloud toolbar

- Source/Chatbook/Actions.wl
> Bugfix: FIx StopChat button failures in cloud

- Source/Chatbook/CreateChatNotebook.wl
- Source/Chatbook/Sandbox.wl
- Source/Chatbook/SendChat.wl
* Make sure `QuantityArray[...]` formats when it comes out of the sandbox
* Suppress UTF-8 encoding messages
> Additional minor fixes

- Source/Chatbook/Explode.wl
- Source/Chatbook/Formatting.wl
- Source/Chatbook/Serialization.wl
Before/After comparison: https://www.wolframcloud.com/obj/rhennigan/Published/FormatUpdateTesting.nb
> Misc formatting fixes and improvements

- Source/Chatbook/Sandbox.wl
This allows the LLM to display things like `Grid[...]` instead of just writing out the full input form:
> Create a URI handle for any expressions that have non-trivial formatting

- Source/Chatbook/Formatting.wl
> Bugfix: Handle escaped markdown characters correctly

- Source/Chatbook/Formatting.wl
> Bugfix: Fix some bad/weird spacing in inline code and WL code blocks

- Developer/Resources/WorkspaceStyles.wl
- FrontEnd/StyleSheets/Chatbook.nb
- FrontEnd/StyleSheets/Wolfram/WorkspaceChat.nb
- Source/Chatbook/ChatModes/ContentSuggestions.wl
- Source/Chatbook/ChatModes/ShowCodeAssistance.wl
- Source/Chatbook/ChatModes/UI.wl
- Source/Chatbook/Storage.wl
> Display chat title in toolbar

- Source/Chatbook/ChatModes/ContentSuggestions.wl
- Source/Chatbook/ChatState.wl
- Source/Chatbook/CommonSymbols.wl
- Source/Chatbook/PromptGenerators/VectorDatabases.wl
- Source/Chatbook/SendChat.wl
> Bugfix: Show download progress indicator when generating suggestions

- FrontEnd/TextResources/ChatbookStrings.tr
- FrontEnd/TextResources/ChineseSimplified/ChatbookStrings.tr
- FrontEnd/TextResources/ChineseTraditional/ChatbookStrings.tr
- FrontEnd/TextResources/French/ChatbookStrings.tr
- FrontEnd/TextResources/Japanese/ChatbookStrings.tr
- FrontEnd/TextResources/Korean/ChatbookStrings.tr
- FrontEnd/TextResources/Spanish/ChatbookStrings.tr
- Scripts/InstallTestDependencies.wls
- Source/Chatbook/ChatModes/UI.wl
> First pass at the "Sources" menu

- Source/Chatbook/ChatModes/UI.wl
> Bugfix: Fix vertical alignment for chat input field

- Source/Chatbook/ChatModes/UI.wl
> Bugfix: Fixed undefined history search view

- Source/Chatbook/ChatMessageToCell.wl
- Source/Chatbook/ChatModes/UI.wl
- Source/Chatbook/SendChat.wl
> Bugfix: Enable code assist rafts in WL code blocks

- PacletInfo.wl
- Source/Chatbook/Formatting.wl
> Bugfix: Make new code block templates work in cloud

- Source/Chatbook/Formatting.wl
> Bugfix: Enable code captions in code blocks

- Scripts/Common.wl
- Source/Chatbook/Formatting.wl
> Bugfix: Ensure entity related boxes are formatted when nested

- Source/Chatbook/ResourceInstaller.wl
A version of the dialog that is dark-mode aware.
> Update URL prompt dialog

- Source/Chatbook/CloudToolbar.wl
> Fix Cloud toolbar inserting cell only at the bottom of a noteboook

- Source/Chatbook/PreferencesContent.wl
> Bugfix: align connect buttons in preferences panel
