Source/Chatbook.wl
Source/Errors.wl
Source/UI.wl

This is mostly intended to be a flexible way to experiment which the UX around which cell styles get included in the chat context.

feature: Add $ChatContextCellStyles for specifying custom cell styles to include as context

---

Source/Serialization.wl
Source/UI.wl

Here's an example of how some cells get serialized:
Note: I think we should have a way to specify styles to exclude, rather than include (i.e. `$ChatContextCellStyles`). It would be confusing to a user why the chat would be completely unaware of the previous cells by default:

Cell to string converters

---

Developer/Resources/Styles.wl
Developer/StylesheetBuilder.wl
FrontEnd/StyleSheets/Chatbook.nb
Source/Chatbook/Actions.wl

This is just a basic implementation to generate a `ChatObject` from a chat output cell using the menu:
If `CreateChat` is undefined, it copies a `Dataset` containing the messages instead.

Hooked up `CopyChatObject` action to chat output menu

---

Developer/Resources/Styles.wl
FrontEnd/StyleSheets/Chatbook.nb

This reserves '/' for future use.
@theodoregray @chriswolfram @rhennigan FYI — If you've got muscle memory for typing '/', be advised ' is the new way.

feature: Use single quote instead of '/' to create new chat input cells

---

Source/Chatbook/CreateChatNotebook.wl

This PR changes `CreateChatNotebook` so that it will inline the stylesheet when evaluating in cloud. It seems like cloud notebooks cannot see paclet stylesheets, but they do work inline:

Inline the stylesheet when in cloud

---

Developer/Resources/Styles.wl
FrontEnd/StyleSheets/Chatbook.nb
Source/Chatbook/Actions.wl
Source/Chatbook/Serialization.wl

This fixes an issue where inline code could fail to format due to timing out while loading DefinitionNotebookClient for a dependent function:
This PR removes the dependency on that function and should render chat outputs a bit faster overall.

Improve formatting of inline code to avoid potential pink boxing

---

Source/Chatbook/Actions.wl

The auto assistance chat was broken in an earlier update so that it wasn't including output cells.

Include outputs in auto assist

---

Assets/AIAssistant/Prompts/Default.md
Source/Chatbook/Actions.wl
Source/Chatbook/Serialization.wl

It still has a very hard time following this rule:
```
* ALWAYS surround inline code with double backticks to avoid ambiguity with context names: ``MyContext`MyFunction[x]``
```
However, I added some extra heuristics to handle this for many cases:

55 improve prompting so that backticks in text or inline code do not break formatting

---

Source/Chatbook/UI.wl

Opening 'Advanced Settings' from the cell dingbat typically attaches to the _right_ side:
Opening 'Advanced Settings' from the notebook toolbar dingbat typically attaches to the _left_ side:

polish: Prevent the 'Advanced Settings' submenu from touching the right notebook window edge

---

Developer/Resources/Styles.wl
FrontEnd/StyleSheets/Chatbook.nb

Bugfix: Fix cell dingbats for chat block dividers in cloud showing as an empty string

---

LLMConfiguration/Personas/Birdnardo/LLMConfiguration.wl
LLMConfiguration/Personas/CodeAssistant/LLMConfiguration.wl
LLMConfiguration/Personas/CodeWriter/LLMConfiguration.wl
LLMConfiguration/Personas/PlainChat/LLMConfiguration.wl
LLMConfiguration/Personas/RawModel/LLMConfiguration.wl
LLMConfiguration/Personas/Wolfie/LLMConfiguration.wl
Source/Chatbook/Actions.wl
Source/Chatbook/UI.wl

* Descriptions are now shown for listed personas
* The 'Inherited' value for Default LLM Evaluator and Automatic Result Analysis no longer displays as a special state; instead the default value ('Chat Assistant', 'True') is shown.
* Fixed icons in Default LLM Evaluator dropdown not displaying correctly.
* The unfinished 'LLM Service Providers' section has been temporarily removed.

feature/hotfix: Improve global chat preferences content

---

PacletInfo.wl
Source/Chatbook/Actions.wl

The auto assistance will no longer cancel a normal chat that's currently in progress:
Old behavior:

Fixed `AIAutoAssist` cancelling chats in progress

---

PacletInfo.wl
Source/Chatbook/Actions.wl
Source/Chatbook/Common.wl
Source/Chatbook/CreateChatNotebook.wl
Source/Chatbook/Formatting.wl
Source/Chatbook/FrontEnd.wl
Source/Chatbook/Serialization.wl

To test this, you can set 
```
Wolfram`Chatbook`Actions`Private`$highlightDynamicContent = True
```
and you'll get a purple frame around the part of the chat output that's actually dynamic:
Everything else in the chat output has been written as static content.

Reduce amount of dynamic content in chat output streaming

---

Source/Startup/Begin/BeginStartup.wl

v13.3.1 will include the chat menu items in the FEs built-in listing of menus. So Wolfram/Chatbook doesn't need to add them itself.

bugfix: Prevent duplicated chat menus in v13.3.1 and newer

---

Source/Chatbook/Actions.wl

Normalize UTF-8 characters before parsing the tool request

---

PacletInfo.wl
Source/Chatbook/Formatting.wl

Avoid doing partial string replacements for language names

---

Source/Chatbook/Actions.wl

Evaluating a chat input will now leave a `ChatObject[...]` in `%`:
This was previously giving the `TaskObject[...]` that was used in `URLSubmit`.
This will also now give more useful outputs when using `NotebookEvaluate` on chat notebooks

Give a `ChatObject` as suppressed output when evaluating chat inputs

---

Source/Chatbook/Serialization.wl

This prevents chats from starting with a "---" when a chat delimiter is used:
Old behavior:

Do not serialize "ChatDelimiter" cells

---

PacletInfo.wl
Source/Chatbook/Formatting.wl

Visually there is not a major difference, but this reduces the traffic over MathLink by a couple of orders of magnitude for images.

Use lower resolution for images while streaming dynamic output

---

Source/Chatbook/Formatting.wl

Fix formatting of code blocks that have spaces in the language specification

---

Developer/Resources/Styles.wl
Developer/StylesheetBuilder.wl
FrontEnd/StyleSheets/Chatbook.nb
PacletInfo.wl
Source/Chatbook/Common.wl

This adds the `"Prepend" -> True` rule to the FrontEnd extension so that the stylesheet from the newest installed version of the paclet will be used instead of what's in the layout.
I've also added version numbers to built stylesheets that will be included in the debug data for internal failures, just to verify that the correct stylesheet is actually being used.

Ensure stylesheet from most recent paclet version is used

---

Source/Chatbook/CreateChatNotebook.wl
Source/Chatbook/Sandbox.wl
Source/Chatbook/Tools.wl
Source/Chatbook/Utils.wl

* Allow reading local files by default
* Added "ToolOptions" to chat settings which can override this
* Added `SetToolOptions` as a convenient way to set these options
* Increased the size of string outputs before `Short` will start dropping content
The overall experience is a bit better when asking the LLM to analyze data from files now:
It will still often claim that it cannot read files, so there's still some prompting work to do.
```
SetToolOptions["WolframLanguageEvaluator",  "AllowedReadPaths" -> paths]
SetToolOptions[scope, "WolframLanguageEvaluator",  "AllowedReadPaths" -> paths]
```
The value for `scope` can be a front end object, e.g. `$FrontEnd`, `$FrontEndSession`, `CellObject[...]`, etc. If omitted, `$FrontEnd` is used as the scope.
The value for `paths` can be any of the …

Sandbox evaluator improvements

---

PacletInfo.wl
Source/Chatbook/Actions.wl

This now displays the correct error message:

Fix large input throwing an internal error when assistance is enabled

---

Source/Chatbook/Formatting.wl

Fix lack of indentation in chat code blocks

---

Source/Chatbook/Actions.wl

Here's an example of a notebook that excludes all Text cells from chats:
```
NotebookPut @ Notebook[
{
Cell[ "This cell is included", "CodeText" ],
Cell[ "This cell is not included", "Text" ],
Cell[ "Test message, please ignore", "ChatInput" ]
},
StyleDefinitions -> Notebook[
{
Cell @ StyleData[ StyleDefinitions -> "Chatbook.nb" ],
Cell[
StyleData[ "Text" ],
TaggingRules -> <| "ChatNotebookSettings" -> <| "ExcludeFromChat" -> True |> |>
]
},
StyleDefinitions -> "PrivateStylesheetFormatting.nb"
]
]
```

Support excluding cells via options

---

Source/Chatbook/ToolManager.wl

Fix tool manager icons on Linux

---

Source/Chatbook/Common.wl
Source/Chatbook/Dialogs.wl

The vertical bar in association syntax needs to be escaped when formatting for markdown tables, since that character is used to separate columns:

Fix bug report markdown syntax for associations

---

Developer/Resources/Styles.wl
FrontEnd/StyleSheets/Chatbook.nb

This fixes an issue with the gear menu showing persistently in 14.0:

Fix for gear menu appearing persistently in 14.0

---

Source/Chatbook/Models.wl
Source/Chatbook/UI.wl

Fine tuned OpenAI models will now show up in the model selection menu automatically if snapshot models are enabled in preferences:

Include fine tuned models in menu

---

Source/Chatbook/Serialization.wl

(cherry picked from commit 7080458442f5bc580c30f4447f15fdd7293f4f1a)

Bugfix: incomplete definition for `truncateString`

---

Source/Chatbook/CreateChatNotebook.wl
Source/Chatbook/Main.wl
Source/Chatbook/Sandbox.wl

Add support for `CreateChatNotebook[{Cell[...], ...}]` and exposed the sandbox kernel `LinkObject` as `$SandboxKernel`.

Minor QoL updates

---

Developer/Resources/Styles.wl
Developer/StylesheetBuilder.wl
FrontEnd/StyleSheets/Chatbook.nb
Source/Chatbook/Actions.wl
Source/Chatbook/ChatHistory.wl
Source/Chatbook/Common.wl
Source/Chatbook/Main.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Settings.wl

Added highlighting of included cells when mousing over chat inputs

---

.gitignore
Source/Chatbook/SendChat.wl
Source/Chatbook/Settings.wl
Source/Chatbook/UI.wl

```txt
Now you can change the default endpoint to anything you want. 
```
Hello, this repo is pretty big, I try not to mess with the  current code base but if I do something wrong, feel free to fix it if you have time 
There are typical cases in which the user didn't fetch data from the official OpenAi url but from some kind of proxy, that is why I added this minor change.
By default, the official URL will be used, but now people can freely change it to something else like `http://localhost:8080/v1/chat/completions/`.

feat: improve setting ui in UI.wl, add OpenAi Chat Completion URL settings

---

Source/Chatbook/Actions.wl
Source/Chatbook/SendChat.wl

The `ChatObject` won't display the images, but it at least won't fail with errors:

Temporary workaround for `ChatObject` not supporting multimodal content

---

FrontEnd/StyleSheets/Chatbook.nb
PacletInfo.wl
Source/Chatbook/Formatting.wl

Bugfix: Workaround for multi-line code blocks not parsing correctly in cloud notebooks

---

Source/Chatbook/SendChat.wl

Bugfix: Fix the missing disable button when auto assistance outputs are first created

---

Source/Chatbook/Actions.wl
Source/Chatbook/ChatHistory.wl
Source/Chatbook/SendChat.wl

This would previously yield an internal error:
It now just returns `Null` instead.

Bugfix: Return `Null` instead of generating an internal failure if the current chat input is excluded

---

Source/Chatbook/FrontEnd.wl

Tool responses that contain patterns would issue messages during caching of `openerView`:
This fixes that by wrapping the arguments in `Verbatim` when caching the result.

Bugfix: Avoid messages that occur during bad caching of tool response boxes

---

Source/Chatbook/ChatMessages.wl
Source/Chatbook/SendChat.wl

This is useful if you'd rather get a `Failure[...]` instead of sending chat with less content than you expected:
```
NotebookEvaluate[
CreateChatNotebook[
{ Cell[ ResourceData[ "Alice in Wonderland" ], "Text" ], Cell[ "What's that?", "ChatInput" ] },
"MaxContextTokens" -> Infinity
],
InsertResults -> True
]
```

Feature: MaxContextTokens can be set to `Infinity` to avoid truncation

---

FrontEnd/StyleSheets/Chatbook.nb
Source/Chatbook/Explode.wl

Bugfix: Exploding cells failure when there's a language-agnostic code block

---

PacletInfo.wl
Source/Chatbook/Actions.wl
Source/Chatbook/Main.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Settings.wl

When a user triggers an abort (e.g. using alt-. or the evaluation menu), the asynchronous task would previously keep running, displaying new chat output. However, the code to finalize the chat output had been cancelled, so the cell remained in in an active state even when finished.
This update changes the behavior associated with user aborts that are issued during chat evaluation by immediately evaluating the "StopChat" action. Now a user abort is effectively equivalent to hitting the red "X" button to stop a chat in progress.
This also introduces a new handler function "ChatAbort", which will run during the stop chat cleanup step.

Stop chat if there's a user abort

---

Source/Chatbook/CloudToolbar.wl
Source/Chatbook/Common.wl
Source/Chatbook/PreferencesContent.wl
Source/Chatbook/Services.wl

TODO: The "Reset to Defaults" button doesn't work yet.

Add "Services" tab to cloud preferences

---

Source/Chatbook/Tools/DefaultTools.wl

Bugfix: Use `Import` as a fallback for the WebFetcher tool when `StartWebSession` fails

---

Source/Chatbook/Formatting.wl
Source/Chatbook/Prompting.wl
Source/Chatbook/Serialization.wl

Improve formatting for outputs that contain `$` to denote currency

---

Source/Chatbook/ResourceInstaller.wl
Source/Chatbook/ToolManager.wl
Source/Chatbook/Tools/Common.wl
Source/Chatbook/Tools/DefaultTools.wl

This adds support for some upcoming changes to `LLMTool` which allow specifying an `AppearanceRules` option:

Support `AppearanceRules` for tools

---

Source/Chatbook/Actions.wl
Source/Chatbook/Common.wl
Source/Chatbook/Formatting.wl
Source/Chatbook/Main.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Tools/Common.wl
Source/Chatbook/Tools/DefaultTools.wl

Added `$ChatNotebookEvaluation`, which gives `True` when in a chat notebook evaluation and `False` otherwise. This lets you define alternate tool behavior for `LLMTool`, personas, etc depending on whether or not evaluation is happening in a chat notebook or programmatically.
For example, define an LLMTool that does something different in a chat notebook environment:
```
LLMTool["...", {...}, If[Wolfram`Chatbook`$ChatNotebookEvaluation, f[#], g[#]] &]
```

Feature: Added `$ChatNotebookEvaluation` and fixed some other minor misc issues

---

PacletInfo.wl
Source/Chatbook/PreferencesContent.wl
Source/Chatbook/Services.wl

If the API call to get the model list fails, the model selector in the preferences dialog will now fall back to the input field method instead of generating an internal error.

Bugfix: Handle service API errors better when retrieving model lists for the preferences dialog

---

Source/Chatbook/Formatting.wl

Bugfix: Fixed pink boxing that occurs in cloud when chat outputs contain inline section cells

---

Source/Chatbook/Settings.wl

(cherry picked from commit b7e3a3d10c0c9c4d0cfe0feac0f0081b1e1d09dc)
I'm not sure why I had this version check in the first place.

Bugfix: Make cloud tagging rules inheritence fix version independent

---

Source/Chatbook/Formatting.wl
Source/Chatbook/Main.wl
Source/Chatbook/Sandbox.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Tools/DefaultTools.wl

Support natural language input for the AI in WL evaluator tool

---

Source/Chatbook/Common.wl
Source/Chatbook/Formatting.wl
Source/Chatbook/Prompting.wl
Source/Chatbook/Sandbox.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Serialization.wl
Source/Chatbook/Tools/Common.wl
Source/Chatbook/Tools/DefaultTools.wl
Source/Chatbook/Tools/Tools.wl
Source/Chatbook/Utils.wl

Add syntax to let the AI insert images inline in the evaluator and markdown code blocks

---

Source/Chatbook/Sandbox.wl
Source/Chatbook/SendChat.wl

This also now handles other exceptions, like `TerminatedEvaluation[...]` and kernel quits:

621 an uncaught throw in the evaluator tool gives an internal error

---

Source/Chatbook/Formatting.wl

Bugfix: Fixed internal error that occurs if the AI writes an unbalanced markdown table

---

Source/Chatbook/Formatting.wl

Bugfix: Markdown tables with less than 3 columns were not formatting

---

Source/Chatbook/SendChat.wl

This occasionally appears in chat outputs when using gpt-4-vision. It's clearly a special token used by OpenAI, since the vision model can't read it like other models can:
```
In[1]:= AssociationMap[
Function[
LLMSynthesize[
"Repeat the following string back to me:\nMy favorite token is <|image_sentinel|>!",
LLMEvaluator -> <| "Model" -> #1, "MaxTokens" -> 64 |>
]
],
{ "gpt-3.5-turbo", "gpt-4", "gpt-4-turbo-preview", "gpt-4-vision-preview" }
]
Out[1]= <|
"gpt-3.5-turbo"        -> "My favorite token is <|image_sentinel|>!",
"gpt-4"                -> "My favorite token is <|image_sentinel|>!",
"gpt-4-turbo-preview"  -> "My favorite token is <|image_sentinel|>!",
"gpt-4-vision-preview" -> "\"My favorite token is !\""
|>
```
The fact that it occasionally appears in chat outputs is almost …

Automatically remove the string `"<|image_sentinel|>"` from chat outputs

---

Source/Chatbook/ChatMessages.wl
Source/Chatbook/Models.wl

This update adds support for Claude 3 models, which includes multimodal support:
Claude 3 models will show up in the menu and available to use once the relevant service connection is released.

Add support for Claude 3

---

Source/Chatbook/UI.wl

Fixed an issue where icons specified by a service were not being used in the UI

---

Source/Chatbook/ChatHistory.wl
Source/Chatbook/FrontEnd.wl
Source/Chatbook/Prompting.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Serialization.wl
Source/Chatbook/Settings.wl
Source/Chatbook/Tools/Common.wl
Source/Chatbook/Tools/DefaultTools.wl

* Added "ToolCallExamplePromptStyle" setting, which controls the formatting of tool call example prompts
* Try to use "Simple" tool call method when possible, since it doesn't have the laziness issue that the full JSON spec has
* Fixed another unhandled argument in `chatExcludedQ`
* Fixed a bug in `cellInformation` when a deleted cell object is given
* Added stop token and prompting about ending messages

Improved tool call prompting and switch to gpt-4o as default

---

Source/Chatbook/ChatMessages.wl

- Fixed the generic tokenizer to correctly apply the cached tokenizer for non-graphics inputs.
- This resolves the issue where the generic tokenizer was returning the `NetEncoder` instead of applying it.
Closes #765

Fix: Correct tokenizer application for generic tokenizer

---

Source/Chatbook/Formatting.wl

This fixes the message that appears in the messages window when writing a chat output that has unbalanced quotes in code blocks:

Bugfix: Prevent `ShowStringCharacters` message for partial strings in code blocks

---

Source/Chatbook/PreferencesContent.wl
Source/Chatbook/Services.wl
Source/Chatbook/ToolManager.wl
Source/Chatbook/Tools/Common.wl

* Try to reset services when data is corrupt rather than fail with an internal error.
* Display the underlying `Failure[...]` as a fallback in the preferences UI if resetting also fails.
* Ignore `LLMTool[...]` expressions that were created/installed in later versions of WL that fail when evaluated.

Bugfix: Fix several version compatibility issues

---

Source/Chatbook/Settings.wl

With this change, the model "gpt-4o" with no date specified will be resolved as "gpt-4o-2024-05-13" when text-based tool calling is enabled:
```
In[1]:= CurrentChatSettings[$FrontEnd, "Model"]
Out[1]= <|"Service" -> "OpenAI", "Name" -> "gpt-4o"|>
```
```
In[2]:= AbsoluteCurrentChatSettings[$FrontEnd, "Model"]
Out[2]= <|"Service" -> "OpenAI", "Name" -> "gpt-4o-2024-05-13"|>
```

Bugfix: The latest snapshot of gpt-4o is really bad at textual tool calling

---

Source/Chatbook/Formatting.wl

This fixes an issue where the LLM sometimes incorrectly starts a code block before a tool call (and never closes it), resulting in raw tool call text appearing in the output:

Bugfix: GPT-4o often writes tool calls in a partial code block

---

Source/Chatbook/Common.wl
Source/Chatbook/Main.wl

* Fixed an issue where bug report URLs could have invalid percent-encoded characters
* Prioritize failure info so most important data is less likely to be truncated
* Reverse stack trace to avoid truncating important items
* Increase the allowed size of bug report text

Added `$LastChatbookFailure` and `$LastChatbookFailureText` for easier bug reporting

---

.github/workflows/ExperimentalRelease.yml
Source/Chatbook/ChatState.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Settings.wl

This makes it clear that slow synchronous models like o1-preview are doing their thing instead of there being a hang:

Show progress text for non streaming models

---

Developer/Resources/WorkspaceStyles.wl
FrontEnd/Assets/Extensions/CoreExtensions.nb
FrontEnd/StyleSheets/Chatbook.nb
FrontEnd/StyleSheets/Wolfram/WorkspaceChat.nb

Bugfix: Align chat icons to cell baseline instead of centering vertically

---

Source/Chatbook/Prompting.wl
Source/Chatbook/Sandbox.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Serialization.wl

Fixed several issues with the LLM being unable to properly reference audio/video expressions

---

Source/Chatbook/Serialization.wl

Bugfix: Handle grids that have more alignment specifications than columns

---

Source/Chatbook/PromptGenerators/RelatedDocumentation.wl

e.g. "ResistorColorCode-123" and "FromResistorColorCode-123"

Bugfix: Fix snippet ID parsing collisions for IDs that have overlapping names

---

DarkModeSupport/StyleSheets/Chatbook.nb
DarkModeSupport/StyleSheets/Wolfram/WorkspaceChat.nb
Developer/Resources/WorkspaceStyles.wl
FrontEnd/Assets/Extensions/CoreExtensions.nb
FrontEnd/StyleSheets/Chatbook.nb
FrontEnd/StyleSheets/Wolfram/WorkspaceChat.nb
PacletInfo.wl
Source/Chatbook/Formatting.wl

If a tool call occurs then the Input/Output code blocks within the tool call interface should line wrap at a reasonable width to promote easier reading.

Allow for line wrapping in NA input and output code blocks

---

Source/Chatbook/Serialization.wl

* Fixed an evaluation leak that can occur during rasterization of graphics boxes
* Serialize $CellContext symbols as strings

Minor markdown serialization fixes

---

DarkModeSupport/StyleSheets/Chatbook.nb
DarkModeSupport/StyleSheets/Wolfram/WorkspaceChat.nb
Developer/Resources/Styles.wl
FrontEnd/Assets/Extensions/CoreExtensions.nb
FrontEnd/StyleSheets/Chatbook.nb
FrontEnd/StyleSheets/Wolfram/WorkspaceChat.nb

Remove ChatSystemInput and SideChat styles from discovery via keyboard shortcuts.

Simplify StyleKeyMapping between chat-like cell styles

---

Source/Chatbook/CommonSymbols.wl
Source/Chatbook/SendChat.wl
Source/Chatbook/Tools/ExpressionURIs.wl

The original intention for this rule still works as expected:

Bugfix: Fixed an issue with incorrect inlined expression parsing

---

Source/Chatbook/ChatTitle.wl

Though we request a maximum title length from the LLM, it may hallucinate a longer title, so add some buffer as well.

464549: double the length of allowed NA titles and add buffer length
